# Generated by Django 2.1.7 on 2019-02-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='summary',
            field=models.TextField(default='This is default summary'),
        ),
    ]
